version: "3"

services:
  mongo:
    image: mongo:4.4.4
    container_name: host.docker.internal
    restart: always
    networks:
      - app-network
    volumes:
      - ./data/dev/mongo:/data/db
    ports:
      - "27017:27017"
  api-server:
    build:
      context: .
    container_name: api-server
    image: api-server
    restart: unless-stopped
    depends_on: [mongo]
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGO_URL=mongodb://host.docker.internal:27017/vouches
      - GC_PERIOD_MINUTES=1
      - POH_ADDRESS=0xc5e9ddebb09cd64dfacab4011a0d5cedaf7c9bdb
    volumes:
      - ./logs:/logs
    networks:
      - app-network
    ports:
      - "8080:3000"

networks:
  app-network:
    driver: bridge
