version: "3"

services:
  mongo:
    image: mongo:4.4.4
    container_name: host.docker.internal
    restart: always
    networks:
      - app-network
    volumes:
      - ./data/dev/mongo:/data/db
    ports:
      - "27017:27017"
  api-server:
    build:
      context: .
    container_name: api-server
    image: api-server
    restart: unless-stopped
    depends_on: [mongo]
    env_file:
    - .env
    volumes:
      - ./logs:/logs
    networks:
      - app-network
    ports:
      - "8080:3000"

networks:
  app-network:
    driver: bridge
